apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-deployment
  namespace: demo-namespace-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b-demo
  template:
    metadata:
      labels:
        app: service-b-demo
    spec:
      containers:
      - name: service-b-demo
        image: hishmath/nest-demo-service-b:17
        ports:
        - containerPort: 3000
